### ISSUE TITLE
momentrgb on mitsuba3

### ISSUE THREAD

**Issue by andyyankai** [WeiPhil/OptimisedPathSpaceRegularisation#1]
Hi Philippe, May I ask if there is an implementation of momentrgb on mitsuba3?
Thanks!

**Comment by WeiPhil** [comment]
Hi Kay Yan, 
There is no direct implementation of `momentrgb` in mitsuba3 but you can easily write your own by looking up the `moment` integrator.
Essentially, in the `sample` function, instead of returning XYZ values, you want to get the corresponding sRGB values using mitsuba's `xyz_to_srgb` function for example, that's it :)
